### ISSUE TITLE
Fortran runtime error on Ubuntu 16.04

### ISSUE THREAD

**Issue by IdoBar** [JiscaH/sequoia#1]
Hi, 

I'm trying to run Sequoia on an Ubuntu server (16.04, running Microsoft R Open 3.3.2, with the current github version of Sequoia, 0.5).
This is my command:
`ParOUT <- sequoia(GenoFile = GenoDataFile,LifeHistFile = "LifeHistFile_assigned_SA.txt", NumSibRounds=10, MaxSibshipSize=10000, MaxMismatch = 20, WriteFiles = TRUE)`

And that's the output:
```
At line 7488 of file Sequoia.f90
Fortran runtime error: No such file or directory
```

I do get AgePriors.txt and SequoiaSpecs.txt in sequoiaOUT/ folder, so these functions work.

Same function with the same data works on windows.

Thanks, Ido

**Comment by JiscaH** [comment]
Hi Ido,

I think the problem is that it should read

sequoia(GenoFile = "GenoDataFile.txt", ....)

Please note that Sequoia is now also on CRAN, so you can download a 
slightly newer version via the standard install.packages(). That version 
works fine on Lubuntu 16, but for some reason not reliably on Debian, so 
I'm not sure if it will work for you. I am working on a fix, and hope to 
have that on CRAN in a few days.

The CRAN version doesn't rely on reading/writing to files, which so 
should hopefully avoid problems like you're having. You can find the 
updated vignette on https://CRAN.R-project.org/package=sequoia 
<https://cran.r-project.org/package=sequoia>.

Cheers,
Jisca

**Comment by IdoBar** [comment]
Hi Jisca,

It's not a problem with the file name (the GenoDataFile is just a character string containing the file name and location) and as I said, it's working perfectly under Windows.
I'll try the CRAN version and will see if it's working (indeed it was a bit strange having to save my objects to file, rather than just pointing to them in the function).

Thanks, Ido

**Comment by JiscaH** [comment]
Hello Ido,

A tarball of the new version is now available on CRAN, 
https://cran.r-project.org/package=sequoia . It may take a few days 
until they update the windows version.

Please don't hesitate to contact me with any further questions or comments.

Kind regards,
Jisca

**Comment by IdoBar** [comment]
Hi Jisca,

I tried the new CRAN version (v0.8.1), using data.frames for GenoData and LifeHistData inputs, however, this time I get a different error:
```
Error in r[i1] - r[-length(r):-(length(r) - lag + 1L)] : 
  non-numeric argument to binary operator
```

Seems to me like it should have been `r[i,1]` in the code, but I can't verify it.

I'll roll  back to the github version for now and work on windows.

Thanks, Ido

**Comment by JiscaH** [comment]
Hi Ido,

I am so sorry about this! The bit of code is not mine but one of the 
functions I'm calling - I'm just not sure which.

Two likely causes:
- The data is not read into R properly. If you're using the 
GenotypeData.txt you made earlier, please use
GM <- as.matrix(read.table("GenotypeData.txt", row.names=1))

-  There is an NA, or other non-number, in either GenoData or 
LifeHistData. Could you please check if this is the case, and if so, 
replace the NA's (or otherwise) by any negative number? I've tried out 
putting NA's in various places in the test datasets but can't replicate 
the problem, so I'm afraid I can't be more specific.

Does the example code at the bottom of ?sequoia work OK for you?

If you want, I can have a look at your data and try to figure out what 
the problem is; I promise I would delete the data straight afterwards.

I hope this helps,
Jisca

**Comment by IdoBar** [comment]
Hi Jisca,

Thank you for your help, the issue was (as you've suggested), due to character values in LifeHistData (both Year and Sex were read as characters from the file).
It is working now using the recent CRAN version.

Thanks, Ido
