### ISSUE TITLE
R version for sequoia

### ISSUE THREAD

**Issue by leonvarhan** [JiscaH/sequoia#15]
Hi, 
Could you please clarify what version of R I should install to run sequoia?
I have tried 4.2.0 and  4.0.0 and in both cases I get the message  "package ‘sequoia’ is not available (for R version 4.0.0)".
Thank you so much!!!!!!!!
Leo

**Comment by JiscaH** [comment]
Dear Leo,

This is unfortunately a confusing error message from R - Sequoia is currently not available from CRAN  for any R version, only here on GitHub. The reason is some memory leak errors according to the CRAN tests that I haven't managed to all reproduce yet in the limited time I've had available in the last months. 

The version available here should work fine though!

**Comment by leonvarhan** [comment]
Hi Jisca, 
Thank you so much for the response.  I don’t have a lot of experience with R., but I installed it with  remotes::install_github("JiscaH/sequoia", ref="stable")
and it seems to have worked.  I am working on a mac computer and R version 4.2.0.   

Do I also need pre-compiled .zip binary file of the development version? 
I truly appreciate your help!
Leo
