### ISSUE TITLE
segmentation fault error in Sequoia

### ISSUE THREAD

**Issue by walla296** [JiscaH/sequoia#7]
Hi, 
I'm running a large dataset in sequoia that is exiting with the following error:
Sibships - Initial Total LL :
[1] -232355
Round 01 end, Total LogLik:
[1] -228607.6
No. dams, sires (incl. dummies):
[1] 362 362

 *** caught segfault ***
address (nil), cause 'unknown'

Traceback:
 1: SeqParSib(ParSib = "sib", Specs = Specs, GenoM = GenoM, LhIN = LifeHistData[,     1:3], AgePriors = Ag$
 2: sequoia(GenoM = GenoM, LifeHistData = LH, MaxSibIter = 10, MaxMismatch = 10,     UseAge = "yes", FindM$
An irrecoverable exception occurred. R is aborting now ...
/var/spool/slurmd/job34109895/slurm_script: line 25: 164736 Segmentation fault      (core dumped) Rscript $

Other, smaller, data files complete normally. I have reproduced this error across R console v3.5.1 and RStudio v1.1.456 on my MAC running Sierra, as well as on an HPC. In all cases, the package runs normally most of the way through the analysis before exiting with the seg fault error. Hoping to find a fix for this, thanks for any suggestions!

**Comment by JiscaH** [comment]
Oops! That shouldn't happen obviously.  How many individuals & SNPs are in the dataset? I will make a mock dataset tomorrow (European time) to see if I can reproduce the issue.

You could try the following options when running sequoia():
- FindMaybeRel = FALSE (if you changed the default)
- CalcLLR = FALSE (although I don't think the problem lies there)
- quiet = 'verbose' (to get more detail on where exactly the crash is happening)

I assume this is sequoia version 1.3.3, as on CRAN? Version 1.3.6 on here may or may not have the same issue, but I don't have access to a Mac to compile it for you. 

Cheers,
Jisca

**Comment by walla296** [comment]
Hi Jisca,
Thanks for the quick response and suggestions- I¹ll try them now. I have
2,549 individuals and 557 SNPs in the file.

Cheers,
Liz

**Comment by JiscaH** [comment]
Hello Liz,
I've used dataset of that size & larger on many occasions (up to 6000 indiv), so that in itself can't be the cause of the problem!

Jisca

**Comment by walla296** [comment]
Okay, thanks. Just sent you the data file. The original run parameters were: MaxSibIter = 10, MaxMismatch = 10, UseAge = "yes", FindMaybeRel = TRUE, CalcLLR = TRUE, quiet = FALSE.
After changing to FindMaybeRel = FALSE, CalcLLR = FALSE , quiet = 'verbose', as you suggested, RStudio still aborted the session. the following was displayed just before the crash:
Round 2 start
Finding pairs...
Clustering...
Merge clusters...
Sibship parent replacement...
Grow clusters...
